function result = slx_model_status(model_name)
%SLX_MODEL_STATUS Return general loaded/dirty/runtime state for one model.

    model_name = char(model_name);
    result = struct( ...
        'model_name', model_name, ...
        'loaded', false, ...
        'dirty', '', ...
        'file_name', '', ...
        'fast_restart', '', ...
        'solver', '', ...
        'start_time', '', ...
        'stop_time', '', ...
        'ok', true, ...
        'error_message', '');

    try
        result.loaded = bdIsLoaded(model_name);
        if ~result.loaded
            return;
        end
        result.dirty = char(get_param(model_name, 'Dirty'));
        result.file_name = char(get_param(model_name, 'FileName'));
        result.fast_restart = char(get_param(model_name, 'FastRestart'));
        result.solver = char(get_param(model_name, 'Solver'));
        result.start_time = char(get_param(model_name, 'StartTime'));
        result.stop_time = char(get_param(model_name, 'StopTime'));
    catch ME
        result.ok = false;
        result.error_message = char(ME.message);
    end
end
