function result = slx_solver_audit(model_name, include_model_solver, include_simscape_solver, include_diagnostics)
%SLX_SOLVER_AUDIT Read solver settings from model and solver configuration blocks.

    if nargin < 2, include_model_solver = true; end
    if nargin < 3, include_simscape_solver = true; end
    if nargin < 4, include_diagnostics = true; end

    load_system(char(model_name));

    model_solver = struct();
    if logical(include_model_solver)
        model_solver = struct( ...
            'SolverType', get_param(char(model_name), 'SolverType'), ...
            'Solver', get_param(char(model_name), 'Solver'), ...
            'MaxStep', get_param(char(model_name), 'MaxStep'), ...
            'RelTol', get_param(char(model_name), 'RelTol'), ...
            'AbsTol', get_param(char(model_name), 'AbsTol'), ...
            'StopTime', get_param(char(model_name), 'StopTime'));
    end

    solver_blocks = {};
    if logical(include_simscape_solver)
        matches = find_system(char(model_name), 'LookUnderMasks', 'all', 'MaskType', 'Solver Configuration');
        for i = 1:numel(matches)
            solver_blocks{end + 1, 1} = struct( ... %#ok<AGROW>
                'block_path', char(matches{i}), ...
                'solver_type', '', ...
                'sample_time', '', ...
                'local_solver', '', ...
                'missing_expected_params', {{}});
        end
    end

    diagnostics = struct();
    if logical(include_diagnostics)
        diagnostics = struct( ...
            'ConsistencyChecking', get_param(char(model_name), 'ConsistencyChecking'), ...
            'SolverPrmCheckMsg', get_param(char(model_name), 'SolverPrmCheckMsg'));
    end

    result = struct( ...
        'ok', true, ...
        'model_solver', model_solver, ...
        'solver_type', i_get_or_default(model_solver, 'SolverType'), ...
        'max_step', i_get_or_default(model_solver, 'MaxStep'), ...
        'rel_tol', i_get_or_default(model_solver, 'RelTol'), ...
        'abs_tol', i_get_or_default(model_solver, 'AbsTol'), ...
        'stop_time', i_get_or_default(model_solver, 'StopTime'), ...
        'diagnostics', diagnostics, ...
        'solver_config_blocks', {solver_blocks}, ...
        'suspicions', {{}});
end

function value = i_get_or_default(data, field_name)
    if isstruct(data) && isfield(data, field_name)
        value = char(string(data.(field_name)));
    else
        value = '';
    end
end
